---
title: "Oxidized Phospholipidomics"
---

## **提取**

### 血浆或血清

1.  **100μL血浆/血清**+**300μL H2O+960μL MTBE/MeOH（5:1；v/v）**（15:0 PE母液浓度为20微摩。若复溶体积为100微，则加入5微15:0 PE，若复溶体积为200微，则加入10微15:0 PE）\ 

2.  涡旋60 s，超声处理10分钟（4°C水浴），在4°C 3000 rpm离心15分钟，然后取上清液（500μL）。在剩余溶液中加入500μL MTBE进行再萃取\

3.  第二步共**重复3次**，合并上清液（1.5mL），然后用真空浓缩器在4°C下蒸发至干\

4.  重组：100μL MeOH复溶 

::: callout-tip
## Note

**复溶的量根据自己实验需求决定**
:::

### 培养的细胞

1.  将细胞（5\*106个细胞/样品）与400μL水混合，然后涡旋30秒，在液氮中孵育1分钟。在室温下解冻并超声处理10分钟。重复冻融循环三次\

2.  在13000rpm和4°C下离心15分钟，然后取10μL上清液，使用BCA试剂盒测量蛋白质浓度\

3.  向样品中加入960μL MTBE/MeOH（5:1；v/v）\

4.  涡旋60 s，超声处理10分钟（4°C水浴），在3000 rpm和4°C下离心15分钟，然后取上清液（500μL）。在剩余溶液中加入500μL甲基叔丁基醚\

5.  重复第四步3次，合并上清液，然后用真空浓缩器在4°C下蒸发至干\

6.  重组：100μL MeOH

### 动物组织样本

1.  将组织称重并在H2O（200μL H2O，约10mg组织）中匀浆**三个循环**（每个循环：5500rpm，20s，重复三次）\

2.  在13000rpm和4°C下离心15分钟；取10μL上清液，用H2O稀释10-20倍，用BCA试剂盒测定蛋白质浓度\

3.  200μL均质组织溶液+200μL H2O+960μL MTBE/MeOH（5:1；v/v）\

4.  涡旋60 s，超声处理10分钟（4°C水浴），在3000 rpm和4°C下离心15分钟，然后取上清液（500μL）。在剩余溶液中加入500μL甲基叔丁基醚\

5.  第四步共**重复3次**，合并上清液（1.5mL），然后用真空浓缩器在4°C下蒸发至干\

6.  重组：100μL MeOH

## 定磷

将复溶的样品4℃下14000rpm离心30min并转移至另一EP管中，取10μL定磷。

::: callout-note
## Note

**注意选择合适离心管,离心使用1.5mL离心管，2mL离心管可能会导致样品有沉淀。**
:::

### **试剂：819负20度冰箱**

**1. 1mM NaH2PO4（Sigma Aldrich#s8282）FW:119.98**\

- 配制：11.99mg/100mLddH2O\

**2. 70%HClO4（Sigma Aldrich#380083）**\

- 因高氯酸具有极强的腐蚀性，故量取高氯酸时，需十分小心。\

**3. 5%Na2MoO4·2H2O（Sigma Aldrich#M1003）**\

- 配制：2.5g/100mLddH2O，可将溶液分装，置于-20℃保存。\

**4. 10%抗坏血酸（Sigma Aldrich#A5960）**\

- 1g/10mLddH2O（足够80个样品使用），现用现配，避光。

::: callout-important
## 警告

**用完试剂请放回！！！**
:::

### **原理**

在酸性环境下，定磷试剂中的钼酸钠以钼酸形式与样品中的磷酸反应生成磷钼酸，当还原剂存在时，磷钼酸会立即转变成蓝色的还原产物—钼蓝，钼蓝最大的光吸收在650-660nm波长处。当使用抗坏血酸还原剂时，测定的最适范围为1-10微克无机磷。（测定样品总磷量时需先使用硫酸或高氯酸将其消化为无机磷再进行测定）

### 步骤

1.  将10μL的样品置于玻璃管中，加入125μL的70%HClO4溶液，放置于170℃油浴中加热20-40min（依据脂质浓度调整加热时间），加热结束时，样品澄清。 

2.  在加热样品的过程中，按照下表制备标准曲线 @tbl-letters，各个组分需涡旋充分混匀。\

| 标准曲线 | 70% HClO4 | dd H2O | 2.5% Na2Mo4·2H2O | 10% 抗坏血酸 | 1mM NaH2PO4 (add last) |
|:----------:|:----------:|:----------:|:----------:|:----------:|:----------:|
|    0     |   125μL   | 825μL  |      125μL       |    125μL     |          0μL           |
|  4.16μM  |   125μL   | 820μL  |      125μL       |    125μL     |          5μL           |
|  12.5μM  |   125μL   | 810μL  |      125μL       |    125μL     |          15μL          |
|  20.8μM  |   125μL   | 800μL  |      125μL       |    125μL     |          25μL          |
|  29.2μM  |   125μL   | 790μL  |      125μL       |    125μL     |          35μL          |
|  37.5μM  |   125μL   | 780μL  |      125μL       |    125μL     |          45μL          |
|  54.2μM  |   125μL   | 760μL  |      125μL       |    125μL     |          65μL          |

: **定磷配置表** {#tbl-letters}

3.  将样品取出冷却至室温后，加入825μLddH2O、125μLNa2MoO4·2H2O，最后加入125μL10%抗坏血酸，充分混匀。

4.  将样品和标准品同时放入沸水浴中加热10min后取出放置于冰上，转移200μL至96孔板中，使用酶标仪检测660nm波长处的吸光度值，将所测的吸光度值代入标准曲线求得含磷浓度，进而计算磷量。

## 制样

1.  固定磷量上样: 取20nmol Pi样本放置于液相小瓶中，加入甲醇补足体积至40μL，加入2μL氘代PE内标。（16:0-d31-18:1 PE：母液浓度为20μM）。

2.  固定体积上样: 直接取40μL样品上样，加入2μL氘代PE内标。

::: callout-warning
## 友情提示

是否需要制作QC样品？个人建议：**制作QC！！！**
:::

## 氧化磷脂组学液质条件

1.  检测摸式：**负离子**

2.  质量范围：**114-1700 Da**

3.  液相分析条件

-   色谱柱：**Waters Premier ACQUITY BEH HILIC (100×2.1 mm, 1.7 μm)**
-   柱温：**40 ℃**
-   流动相：
    -   A相:**乙腈:水(95:5)+10 mM甲酸铵**
    -   B相:**乙腈:水(50:50)+10 mM甲酸铵**
-   洗脱程序：@tbl-le

| Time   | Flow\[ml/min\] |  B%   | C%  | Curve |
|:-------|:--------------:|:-----:|:---:|:-----:|
| 0.000  |      0.25      |  0.0  | 0.0 |   5   |
| 10.000 |      0.25      | 35.0  | 0.0 |   5   |
| 10.100 |      0.25      | 100.0 | 0.0 |   5   |
| 13.000 |      0.25      | 100.0 | 0.0 |   5   |
| 13.100 |      0.25      |  0.0  | 0.0 |   5   |
| 22.000 |      0.25      |  0.0  | 0.0 |   5   |

: **洗脱程序** {#tbl-le}

-   进样量：2 uL(按具体情况调整)

4.  质谱分析条件

-   源气参数：

    -   离子源：电喷雾离子化源（ESI）

    -   Spray Voltage：负离子, -2.8 kV

    -   S-lens RF level：65

    -   Capillary temperature：350 ℃

    -   Aux gas heater temp：320 ℃

    -   鞘气：30 arb

    -   辅助气：15 arb

    -   反吹气：0 arb

-   质谱采集参数：请考虑是否需要采集二级。

    -   Full MS: Resolution: 70000

    -   AGC: 3e6

    -   MIT: 100 ms

    -   Full MS/dd-MS2: Resolution: 17500

    -   AGC: 1e5

    -   MIT: 50 ms

    -   Top N:5; Isolation window:1.0m/z

    -   (N)CE:20, 30, 40

    -   dd Settings: Minimum AGC: 8.00e3

    -   Intensity thresh: 1.6e5

    -   Dynamic exclus: 10.0s
